
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */

public class FormJavaPbo extends javax.swing.JFrame {

    String NamaPenyewa;
    String CodeRoom;
    String JenisKamar;
    
    int Tarif;
    int LamaInap;
    int Diskon;
    int JumlahBayar;
    /**
     * Creates new form FormJavaPbo
     */
    public FormJavaPbo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jumlah_bayar = new javax.swing.JTextField();
        coderoom = new javax.swing.JComboBox<>();
        txtNamaPenyewa = new javax.swing.JTextField();
        jenis_kamar = new javax.swing.JTextField();
        xtarif = new javax.swing.JTextField();
        lamainap = new javax.swing.JTextField();
        diskon = new javax.swing.JTextField();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("FORM BOOKING KAMAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel2.setText("Nama Penyewa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel3.setText("Kode Kamar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel4.setText("Jenis Kamar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel5.setText("Tarif/Malam");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel6.setText("Lama inap");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel7.setText("Diskon");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel8.setText("Jumlah Bayar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jumlah_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_bayarActionPerformed(evt);
            }
        });
        getContentPane().add(jumlah_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 220, 30));

        coderoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mawar Basic - 001", "Mawar Economy - 002", "Mawar Vip - 003", "Mawar V-Vip - 004", "Mawar Extra V-Vip - 005" }));
        coderoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coderoomActionPerformed(evt);
            }
        });
        getContentPane().add(coderoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 220, 30));

        txtNamaPenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPenyewaActionPerformed(evt);
            }
        });
        txtNamaPenyewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaPenyewaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaPenyewaKeyTyped(evt);
            }
        });
        getContentPane().add(txtNamaPenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 220, 30));

        jenis_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_kamarActionPerformed(evt);
            }
        });
        getContentPane().add(jenis_kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 220, 30));
        getContentPane().add(xtarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 220, 30));

        lamainap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamainapActionPerformed(evt);
            }
        });
        lamainap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lamainapKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lamainapKeyTyped(evt);
            }
        });
        getContentPane().add(lamainap, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 220, 30));
        getContentPane().add(diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 220, 30));

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coderoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coderoomActionPerformed
        // Kode Kamar
        if (coderoom.getSelectedIndex() == 0) {
            jumlah_bayar.setText("");
//            coderoom.setSelectedIndex(0);
//            txtNamaPenyewa.setText("");
            jenis_kamar.setText("");
            xtarif.setText("");
            lamainap.setText("");
            diskon.setText("");
            
            
        }
        else if(coderoom.getSelectedIndex() == 1){
            JenisKamar = "Mawar Basic";
            Tarif = 400000;
        }
        
        else if(coderoom.getSelectedIndex() == 2){
            JenisKamar = "Mawar Economy";
            Tarif = 500000;
            
        } 
        else if(coderoom.getSelectedIndex() == 3){
           JenisKamar = "Mawar VIP";
            Tarif = 600000;
        } 
        else if(coderoom.getSelectedIndex() == 4){
            JenisKamar = "Mawar VVIP";
            Tarif = 800000;
            
        } 
        else if(coderoom.getSelectedIndex() == 5){
            JenisKamar = "Mawar Extra VVIP";
            Tarif = 1400000;
            
        }
        jenis_kamar.setText(String.valueOf(JenisKamar));
        xtarif.setText(String.valueOf(Tarif));
        jenis_kamar.setEditable(false);
        xtarif.setEditable(false);
        diskon.setEditable(false);
        jumlah_bayar.setEditable(false);
//        else {
//        }
        
    }//GEN-LAST:event_coderoomActionPerformed

    private void lamainapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamainapActionPerformed
        // Biaya inap set 
        LamaInap = Integer.parseInt(lamainap.getText());
        
        if (coderoom.getSelectedIndex() == 1 ) {
          Diskon = LamaInap * Tarif*2/100;
          JumlahBayar = Tarif - Diskon;
          
        } 
        else if (coderoom.getSelectedIndex() == 2 ) {
          Diskon = LamaInap * Tarif*3/100;
          JumlahBayar = Tarif - Diskon;
        }
        
        else if (coderoom.getSelectedIndex() == 3 ) {
          Diskon = LamaInap * Tarif*4/100;
          JumlahBayar = Tarif - Diskon;
        }
        
        else if (coderoom.getSelectedIndex() == 4 ) {
          Diskon = LamaInap * Tarif*5/100;
          JumlahBayar = Tarif - Diskon;
        }
        
        else if (coderoom.getSelectedIndex() == 5 ) {
          Diskon = LamaInap * Tarif*60/100;
          JumlahBayar = Tarif - Diskon;
        }
        
      
        
        diskon.setText(String.valueOf(Diskon));
        jumlah_bayar.setText(String.valueOf(JumlahBayar));
    }//GEN-LAST:event_lamainapActionPerformed

    private void jumlah_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_bayarActionPerformed

    private void jenis_kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_kamarActionPerformed
        // TODO add your handling code here:
        if (coderoom.getSelectedIndex() == 0) {
           coderoom.setSelectedIndex(0);
            
        }
        
    }//GEN-LAST:event_jenis_kamarActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
       
        jumlah_bayar.setText("");
        coderoom.setSelectedIndex(0);
        txtNamaPenyewa.setText("");
        jenis_kamar.setText("");
        xtarif.setText("");
        lamainap.setText("");
        diskon.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void txtNamaPenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPenyewaActionPerformed
        // TODO add your handling code here:
//        NamaPenyewa = txtNamaPenyewa.getText();
//        if(NamaPenyewa.equals("")){
//            JOptionPane.showMessageDialog("");
//        }
    }//GEN-LAST:event_txtNamaPenyewaActionPerformed

    private void txtNamaPenyewaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaPenyewaKeyPressed
        // Input nama
        
    }//GEN-LAST:event_txtNamaPenyewaKeyPressed

    private void lamainapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamainapKeyPressed
        // Input durasi lama inap
//        String 
    }//GEN-LAST:event_lamainapKeyPressed

    private void lamainapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamainapKeyTyped
        // TODO add your handling code here:
        
        String mrx = lamainap.getText();
        int length = mrx.length();
        
        
        var c = evt.getKeyChar();
        
        //fungsi untuk anti character        
        if(!Character.isDigit(c)){
            evt.consume();
        }
        
        if(evt.getKeyChar()>='0') {
           if(length>1){
            lamainap.setEditable(false);
           }else{
            lamainap.setEditable(true);
           }
        }
    
      
    }//GEN-LAST:event_lamainapKeyTyped

    private void txtNamaPenyewaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaPenyewaKeyTyped
        // TODO add your handling code here:
        String mrxs = txtNamaPenyewa.getText();
         int length = mrxs.length();
         char c = evt.getKeyChar();
//         if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
//            lamainap.setEditable(true);
//        } else {
//            lamainap.setEditable(false);
//        }
             if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE)) {
                 evt.consume();  // ignore the event if it's not an alphabet
             }
    }//GEN-LAST:event_txtNamaPenyewaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormJavaPbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormJavaPbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormJavaPbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormJavaPbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormJavaPbo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> coderoom;
    private javax.swing.JTextField diskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jenis_kamar;
    private javax.swing.JTextField jumlah_bayar;
    private javax.swing.JTextField lamainap;
    private javax.swing.JTextField txtNamaPenyewa;
    private javax.swing.JTextField xtarif;
    // End of variables declaration//GEN-END:variables
}
